export enum UserRole {
  GUEST = 'GUEST',
  USER = 'USER',
  STAFF = 'STAFF',
  STAFF_SELL_AGENT = 'STAFF_SELL_AGENT',
  STAFF_CHECK_IN = 'STAFF_CHECK_IN',
  STAFF_CONTENT_WRITER = 'STAFF_CONTENT_WRITER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
